#!/bin/bash
# Cursor Hook for AI Code Guard
#
# Generated by `ac-guard install --agent cursor`.
# This file is managed by AI Code Guard — do not edit manually.
#
# Cursor hook format:
# - Input: stdin JSON (tool/command + args)
# - Output: stdout JSON {"permission": "allow/deny"}
# - Exit code: 0 (non-zero may cause Cursor issues)

set -e

# Read input from stdin (Cursor format varies by hook type)
input=$(cat)

# Parse tool call (Cursor uses different formats for different hooks)
tool_name=$(echo "$input" | jq -r '.tool // .command // .name // "unknown"' 2>/dev/null || echo "unknown")

# Build Action guard input JSON (agent identifies the caller in audit records)
action_guard_input=$(jq -n \
    --arg tn "$tool_name" \
    --argjson ti "$(echo "$input" | jq '.args // .arguments // {}' 2>/dev/null || echo '{}')" \
    '{tool_name: $tn, tool_input: $ti, agent: "cursor"}')

# Call Action guard via Python subprocess.
# python_executable is baked at install time so the hook works even when
# Cursor launches it from a shell whose $PATH lacks the project's venv.
action_guard_output=$(echo "$action_guard_input" | "/usr/local/bin/python3" -m ac_guard.action_guard 2>/dev/null || echo '{"decision": "deny"}')

# Extract decision
decision=$(echo "$action_guard_output" | jq -r '.decision // "deny"' 2>/dev/null || echo "deny")

# Cursor does not support "ask" — downgrade to "deny"
if [ "$decision" = "ask" ]; then
    decision="deny"
fi

# Output Cursor expected format
echo "{\"permission\": \"$decision\"}"
