"""Cursor Agent adapter implementation.

Cursor supports Hook capability with limitations:
- Runtime interception (can_block=True)
- Limited ask capability (can_ask=False — treated as deny)

Rule document: .cursor/rules/behavior.mdc (Cursor's .mdc format)
Hook entry: .cursor/hooks/check.sh (stdin/stdout JSON)
"""

from __future__ import annotations

from ai_guard.adapters.base import AgentAdapter, AgentCapabilities
from ai_guard.config.models import BehaviorConfig
from ai_guard.shared.types import FileSpec, wrap_with_managed_block

__all__ = ["CursorAdapter"]


class CursorAdapter(AgentAdapter):
    """Adapter for Cursor AI coding agent."""

    @property
    def name(self) -> str:
        return "cursor"

    @property
    def capabilities(self) -> AgentCapabilities:
        # Cursor has limited ask capability, treated as False
        return AgentCapabilities(can_block=True, can_ask=False)

    def rule_doc_path(self) -> str:
        return ".cursor/rules/behavior.mdc"

    def render_rule_doc(self, behavior: BehaviorConfig) -> str:
        """Render behavior rules as Cursor rule document.

        Cursor uses .mdc format with frontmatter. Output is wrapped
        with managed block markers.
        WP1.3b will add Jinja2 templates for improved formatting.
        """
        lines: list[str] = []

        # Cursor .mdc frontmatter
        lines.append("---")
        lines.append("globs: **/*")
        lines.append("---")
        lines.append("")
        lines.append("## Behavior Constraints")
        lines.append("")
        lines.append(
            "The following rules define what operations are permitted " "or blocked."
        )
        lines.append("")

        # Note about ask capability
        lines.append(
            "> **Note**: This Agent does not support user confirmation prompts. "
            "Require-approval rules are treated as forbidden."
        )
        lines.append("")

        # Render each operation type
        for op_name, op_rules in [
            ("Read", behavior.read),
            ("Write", behavior.write),
            ("Execute", behavior.execute),
        ]:
            lines.append(f"### {op_name} Operations")
            lines.append("")

            if op_rules.forbidden:
                lines.append("**Forbidden** (blocked):")
                for rule in op_rules.forbidden:
                    reason = f" — {rule.reason}" if rule.reason else ""
                    lines.append(f"- `{rule.pattern}`{reason}")
                lines.append("")

            # require_approval treated as forbidden (can_ask=False)
            if op_rules.require_approval:
                lines.append("**Require Approval** → **Blocked** (no ask capability):")
                for rule in op_rules.require_approval:
                    msg = f" — {rule.message}" if rule.message else ""
                    lines.append(f"- `{rule.pattern}`{msg}")
                lines.append("")

            if op_rules.allow:
                lines.append("**Allowed** (permitted):")
                for rule in op_rules.allow:
                    lines.append(f"- `{rule.pattern}`")
                lines.append("")

        content = "\n".join(lines)
        return wrap_with_managed_block(content)

    def hook_files(self, behavior: BehaviorConfig) -> list[FileSpec]:
        """Generate Cursor Hook script.

        Returns a shell script that:
        - Reads stdin JSON (Cursor format)
        - Calls Enforcer for policy decision
        - Returns JSON output

        WP1.3b will add full protocol conversion template.
        """
        hook_content = """#!/bin/bash
# Cursor Hook for AI Guard
# Generated by ai-guard install --agent cursor
# This file is managed by AI Guard — do not edit manually

# Read input from stdin
input=$(cat)

# TODO: Call Enforcer for policy decision (WP2)
# For now, allow all operations
decision="allow"

# Output Cursor expected format
echo "{\"permission\": \"$decision\"}"
"""

        return [
            FileSpec(
                path=".cursor/hooks/check.sh",
                content=hook_content,
                executable=True,
            ),
        ]
