"""OpenCode Agent adapter implementation.

OpenCode supports full Hook capability via plugin events:
- Runtime interception (can_block=True)
- User confirmation prompts (can_ask=True)

Rule document: AGENTS.md
Hook entry: .opencode/plugins/ai-guard.ts (TypeScript plugin)
"""

from __future__ import annotations

from ai_guard.adapters.base import AgentAdapter, AgentCapabilities
from ai_guard.config.models import BehaviorConfig
from ai_guard.shared.types import FileSpec, wrap_with_managed_block

__all__ = ["OpenCodeAdapter"]


class OpenCodeAdapter(AgentAdapter):
    """Adapter for OpenCode AI coding agent."""

    @property
    def name(self) -> str:
        return "opencode"

    @property
    def capabilities(self) -> AgentCapabilities:
        return AgentCapabilities(can_block=True, can_ask=True)

    def rule_doc_path(self) -> str:
        return "AGENTS.md"

    def render_rule_doc(self, behavior: BehaviorConfig) -> str:
        """Render behavior rules as OpenCode rule document.

        Output format is Markdown wrapped with managed block markers.
        WP1.3b will add Jinja2 templates for improved formatting.
        """
        lines: list[str] = []

        # Header
        lines.append("## Behavior Constraints")
        lines.append("")
        lines.append(
            "The following rules define what operations are permitted, "
            "blocked, or require approval."
        )
        lines.append("")

        # Render each operation type
        for op_name, op_rules in [
            ("Read", behavior.read),
            ("Write", behavior.write),
            ("Execute", behavior.execute),
        ]:
            lines.append(f"### {op_name} Operations")
            lines.append("")

            if op_rules.forbidden:
                lines.append("**Forbidden** (blocked):")
                for rule in op_rules.forbidden:
                    reason = f" — {rule.reason}" if rule.reason else ""
                    lines.append(f"- `{rule.pattern}`{reason}")
                lines.append("")

            if op_rules.require_approval:
                lines.append("**Require Approval** (ask user):")
                for rule in op_rules.require_approval:
                    msg = f" — {rule.message}" if rule.message else ""
                    lines.append(f"- `{rule.pattern}`{msg}")
                lines.append("")

            if op_rules.allow:
                lines.append("**Allowed** (permitted):")
                for rule in op_rules.allow:
                    lines.append(f"- `{rule.pattern}`")
                lines.append("")

        content = "\n".join(lines)
        return wrap_with_managed_block(content)

    def hook_files(self, behavior: BehaviorConfig) -> list[FileSpec]:
        """Generate OpenCode TypeScript plugin.

        Returns a TypeScript plugin file that:
        - Intercepts tool calls via OpenCode plugin API
        - Calls Enforcer for policy decision
        - Throws error to block forbidden operations

        WP1.3b will add full protocol conversion template.
        """
        plugin_content = """/**
 * OpenCode Plugin for AI Guard
 *
 * Generated by ai-guard install --agent opencode
 * This file is managed by AI Guard — do not edit manually
 */

export default {
  name: "ai-guard",

  async onToolCall({ tool, args }) {
    // TODO: Call Enforcer for policy decision (WP2)
    // For now, allow all operations
    const decision = "allow";

    if (decision === "deny") {
      throw new Error(`Operation blocked by AI Guard: ${tool}`);
    }

    // Return undefined to allow the operation
    return undefined;
  },
};
"""

        return [
            FileSpec(
                path=".opencode/plugins/ai-guard.ts",
                content=plugin_content,
                executable=False,
            ),
        ]
